version: "3"

services: 
  nginx:
    restart: always
    image: nginx:ftp
    container_name: nginx
    volumes: 
      # - ./file.conf:/etc/nginx/conf.d/file.conf
      - ./data:/var/www/file
    expose: 
      - 8000

